title: Руководство гедеоновца
description: Перевод на русский «Руководства гедеоновца» “The Gideons International Guide Book”
theme: just-the-docs

url: https://gideonsrussia.github.io/guide/

aux_links:
  "Официальный сайт": https://gideons.ru
