title: Руководство гедеоновца
description: Перевод на русский «Руководства гедеоновца» “The Gideons International Guide Book”
lang: ru-RU
theme: just-the-docs

url: https://gideonsrussia.github.io/guide

baseurl: /guide #/notes # the subpath of your site, e.g. /blog
logo: "/assets/images/tgi.svg"

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

aux_links:
  "Официальный сайт": https://gideons.ru

aux_links_new_tab: true

defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/img/card.jpg
